### ISSUE TITLE
Implement a test suite

### ISSUE THREAD

**Issue by Ivan-Johnson** [Ivan-Johnson/LifeLogServer#3]
LifeLog needs a test suite to verify that endpoints function correctly.

**Comment by JohnsonIvan** [comment]
https://flask.palletsprojects.com/en/1.1.x/tutorial/tests/

This seems like a good guide to follow

**Comment by Ivan-Johnson** [comment]
Guess I should stop rewriting history if I'm using GitHub issues :\
