### ISSUE TITLE
Flask's "instance" folder should be relocated

### ISSUE THREAD

**Issue by Ivan-Johnson** [Ivan-Johnson/LifeLogServer#4]
At present, Flasks's "instance" folder is located in the same directory as the source code. It should be located somewhere else because A: it semantically doesn't fit in its current location and B: it complicates the deployment script.

**Comment by JohnsonIvan** [comment]
Changing from "bug" to "enhancement" because everything works as intended; this issue is just a matter of _enhancing_ code maintainability.

**Comment by Ivan-Johnson** [comment]
This was fixed as a side effect of #10.
